{% set name = "metric-learn" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a5dcea221cc2af46212b21974d4d6e64ba211d8e8727b0e9531a55ad8361a496

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpy
    - python >=3.6
    - scikit-learn >=0.20.3
    - scipy

test:
  imports:
    - metric_learn

about:
  home: http://github.com/scikit-learn-contrib/metric-learn
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Python implementations of metric learning algorithms

  description: metric-learn contains efficient Python implementations of several popular supervised and weakly-supervised metric learning algorithms. As part of scikit-learn-contrib, the API of metric-learn is compatible with scikit-learn, the leading library for machine learning in Python. This allows to use all the scikit-learn
    routines (for pipelining, model selection, etc) with metric learning algorithms through a unified interface.
  doc_url: http://contrib.scikit-learn.org/metric-learn/
  dev_url: http://github.com/scikit-learn-contrib/metric-learn

extra:
  recipe-maintainers:
    - bellet
    - perimosocordiae
    - terrytangyuan
    - wdevazelhes
